window.PRINTABLE_SVGS = [
  {
    file: "arrow_l.svg",
    title: "Стрелка влево",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "arrows",
  },
  {
    file: "arrow_r.svg",
    title: "Стрелка вправо",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "arrows",
  },
  {
    file: "arrow_lt.svg",
    title: "Стрелка влево вверх",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "arrows",
  },
  {
    file: "arrow_rt.svg",
    title: "Стрелка вправо вверх",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "arrows",
  },
  {
    file: "arrow_lb.svg",
    title: "Стрелка влево вниз",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "arrows",
  },
  {
    file: "arrow_rb.svg",
    title: "Стрелка вправо вниз",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "arrows",
  },
  {
    file: "arrow_stairs_lt.svg",
    title: "Лестница влево",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "arrows",
  },
  {
    file: "arrow_stairs_rt.svg",
    title: "Лестница вправо",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "arrows",
  },
  {
    file: "camera.svg",
    title: "Камера",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "icons",
  },
  {
    file: "kettle.svg",
    title: "Чайник",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "icons",
  },
  {
    file: "noise.svg",
    title: "Не шуметь",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "icons",
  },
  {
    file: "sofa.svg",
    title: "Диван",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "icons",
  },
  {
    file: "wc.svg",
    title: "Туалет",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "icons",
  },
  {
    file: "wheel.svg",
    title: "Руль",
    dimensions: "200 × 200 mm",
    widthMm: 200,
    heightMm: 200,
    group: "icons",
  },
];
